name: shell commands

on: [push, pull_request]

jobs:
   run-shell-command: 
      runs-on: ubuntu-latest
      steps:
        - name: eccho a string
          run: echo "hello github"
        - name: multiline script
          run: |
             node -v
             npm -v
